version: '3.8'

services:
  application:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: LaravelInertiaVueSpa.Database_2024!
      MYSQL_ROOT_PASSWORD: LaravelInertiaVueSpa.Password_2024!
    ports:
      - "3307:3307"
